
services:
  asterisk:
    build: .
    container_name: asterisk
    restart: unless-stopped
    ports:
      # These generally aren't needed because we're in `host` network_mode, but useful to keep for local dev.
      - "5060:5060/udp"
      - "5060:5060/tcp"
      - "10000-10100:10000-10100/udp"
    volumes:
      - ./config:/etc/asterisk
      - ./scripts:/etc/asterisk/scripts
      - ./provision:/provision
    env_file:
      - hms-env
    healthcheck:
      test: ["CMD", "asterisk", "-rx", "core show version"]
      interval: 30s
      timeout: 10s
      retries: 3
    command: /usr/sbin/asterisk -f
    network_mode: host
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.dect-registration-mode.schedule: "@every 180s"
      ofelia.job-exec.dect-registration-mode.command: "/provision/dect-registration.sh"
      ofelia.job-exec.hms-pjsip.schedule: "@every 60s"
      ofelia.job-exec.hms-pjsip.command: "/provision/hms-pjsip.sh"

  sipcord-bridge:
   build: sipcord-bridge
   image: sipcord-bridge:latest
   container_name: sipcord-bridge
   restart: unless-stopped
   network_mode: host
   env_file:
     - sipcord-env
   volumes:
     - ./sipcord-dialplan.toml:/app/dialplan.toml:ro

  ofelia:
    image: mcuadros/ofelia:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command: daemon --docker
    depends_on:
      - asterisk
     
