[hack]
include => outgoing
include => fun
include => registration
include => hms
include => discord

[groups]
exten => 87,1,Dial(Local/729&Local/7378&Local/739&Local/7883) ; Upstairs
exten => 3767,1,Dial(Local/2663&Local/278&Local/33&Local/3532) ; Downstairs

[fun]
exten => 600,1,Playback(demo-echotest)
 same => n,Echo()
 same => n,Playback(demo-echodone)
 same => n,Goto(s,6)

exten => 3233,1,Playback(/etc/asterisk/sounds/hacktheplanet)
  same => n,Wait(0.5)
  same => n,Hangup()

exten => 3547,1,Answer()
  same => n,AGI(/etc/asterisk/scripts/flipdot-time.sh)
  same => n,Hangup()

[registration]
exten => _100X.,1,NoOp(hack: registering handset/line)
  same => n,Answer()
  same => n,AGI(/etc/asterisk/scripts/register-handset.sh)
  same => n,Wait(10)
  same => n,Hangup()

[hms]
exten => _X.,1,Dial(PJSIP/${EXTEN},30)
#tryinclude extensions-hms.conf

[discord]
exten => 1000,1,Set(CALLERID(num)=0)
 same => n,Dial(PJSIP/sipcord/sip:1000@10.0.0.19:5066)
 same => n,Hangup()

exten => 8000,1,Set(CALLERID(num)=0)
 same => n,Dial(PJSIP/sipcord/sip:8000@10.0.0.19:5066)
 same => n,Hangup()

[outgoing]
exten => 999,1,Dial(PJSIP/${EXTEN}@aaisp-trunk-01157323048)
exten => 112,1,Dial(PJSIP/${EXTEN}@aaisp-trunk-01157323048)
exten => 111,1,Dial(PJSIP/${EXTEN}@aaisp-trunk-01157323048)
exten => 101,1,Dial(PJSIP/${EXTEN}@aaisp-trunk-01157323048)

  
[from-aaisp]
include => fun
include => hms
include => discord

exten => incoming-01157323048,1,Answer()
 same => n,Playback(/etc/asterisk/sounds/external-greeting)
 same => n,WaitExten(5)
 same => n,Playback(/etc/asterisk/sounds/extension-busy)
 same => n,Hangup()
 
exten => incoming-01157323047,1,Answer(),
 same => n,Set(CALLERID(num)=0)
 same => n,Dial(PJSIP/sipcord/sip:8000@10.0.0.19:5066)
 same => n,Hangup()

exten => incoming-emf,1,Answer()
 same => n,Playback(/etc/asterisk/sounds/external-greeting)
 same => n,WaitExten(5)
 same => n,Playback(/etc/asterisk/sounds/extension-busy)
 same => n,Hangup()

