[hack]
exten => _X.,1,NoOp(hack: dialing PJSIP/${EXTEN})
 same => n,Dial(PJSIP/${EXTEN},30)
 same => n,Hangup()

exten => 8500,1,VoiceMailMain()
 same => n,Goto(s,6)

exten => 600,1,Playback(demo-echotest)
 same => n,Echo()
 same => n,Playback(demo-echodone)
 same => n,Goto(s,6)

exten => 1000,1,Set(CALLERID(num)=0)
 same => n,Dial(PJSIP/sipcord/sip:1000@10.0.0.19:5066)
 same => n,Hangup()

exten => 3233,1,Playback(/etc/asterisk/sounds/hacktheplanet)
  same => n,Wait(0.5)
  same => n,Hangup()

exten => 3547,1,Answer()
  same => n,AGI(/etc/asterisk/scripts/flipdot-time.sh)
  same => n,Hangup()

exten => _100X.,1,NoOp(hack: registering handset/line)
  same => n,Answer()
  same => n,AGI(/etc/asterisk/scripts/register-handset.sh)
  same => n,Wait(10)
  same => n,Hangup()


[from-aaisp]
exten => _X.,1,NoOp(hack: dialing PJSIP/${EXTEN})
 same => n,Dial(PJSIP/${EXTEN},30)
 same => n,Hangup()

exten => incoming-01157323048,1,Answer()
 same => n,Playback(silence/1)
 same => n,WaitExten(5)
 same => n,Hangup()
 
exten => incoming-01157323047,1,Playback(/etc/asterisk/sounds/hacktheplanet)
  same => n,Hangup()
