[hack]
exten => _X.,1,NoOp(hack: dialing PJSIP/${EXTEN})
 same => n,Dial(PJSIP/${EXTEN},30)
 same => n,Hangup()

exten => 8500,1,VoiceMailMain()
 same => n,Goto(s,6)

exten => 600,1,Playback(demo-echotest)
 same => n,Echo()
 same => n,Playback(demo-echodone)
 same => n,Goto(s,6)

exten => 1000,1,Set(CALLERID(num)=0)
 same => n,Dial(PJSIP/sipcord/sip:1000@10.0.0.19:5066)
 same => n,Hangup()
