[global]
default-realm=nottinghack.org.uk
debug = 1
verbose = 1
trace = 1

[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0

[transport-tcp]
type=transport
protocol=tcp
bind=0.0.0.0
tcp_keepalive_enable=yes
tcp_keepalive_idle_time=30
tcp_keepalive_interval_time=10
tcp_keepalive_probe_count=5

[aor-single](!)
type=aor
max_contacts=4

[acl]
type=acl
deny=0.0.0.0/0.0.0.0
permit=10.0.0.0/24  ;; vlan 2
permit=10.0.8.0/24  ;; vpn
permit=127.0.0.1/32
permit=80.235.226.218/32 ;; NATd address
permit=81.187.30.118/32  ;; A&A ISP Trunk
permit=81.187.30.116/32  ;; A&A ISP Trunk

#tryinclude pjsip-auth.conf
#tryinclude pjsip-dect.conf
#tryinclude pjsip-vg224.conf
#tryinclude pjsip-hms.conf

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; A&A ISP VoIP (0115 732 3048)
[aaisp-trunk-01157323048]
type = registration
outbound_auth = aaisp-trunk-01157323048
server_uri = sip:voiceless.aa.net.uk:5060
client_uri = sip:+441157323048@voiceless.aa.net.uk
retry_interval = 60
expiration = 3600
contact_user = incoming-01157323048

[aaisp-trunk-01157323048]
type = endpoint
context = from-aaisp
allow = all
outbound_auth = aaisp-trunk-01157323048

[aaisp-trunk-01157323048]
type = identify
endpoint = aaisp-trunk-01157323048
match = voiceless.aa.net.uk

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Sipcord
[sipcord]
type = registration
transport = transport-udp
outbound_auth = sipcord
server_uri = sip:127.0.0.1:5066
client_uri = sip:1000@nottinghack.org.uk
retry_interval = 60
expiration = 3600

[sipcord]
type = endpoint
context = sipcord
allow = all
from_user = sipcord
from_domain = nottinghack.org.uk
outbound_auth = sipcord

[sipcord]
type = auth
auth_type = userpass
username = sipcord
password = sipcord
