[global]
default-realm=nottinghack.org.uk

[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0

[transport-tcp]
type=transport
protocol=tcp
bind=0.0.0.0
tcp_keepalive_enable=yes
tcp_keepalive_idle_time=30
tcp_keepalive_interval_time=10
tcp_keepalive_probe_count=5

[aor-single](!)
type=aor
max_contacts=4

[acl]
type=acl
deny=0.0.0.0/0.0.0.0
permit=10.0.0.0/24  ;; vlan 2
permit=10.0.8.0/24  ;; vpn
permit=127.0.0.1/32

#include pjsip-auth.conf

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Sipcord
[sipcord]
type = registration
transport = transport-udp
outbound_auth = sipcord
server_uri = sip:127.0.0.1:5066
client_uri = sip:1000@nottinghack.org.uk
retry_interval = 60
expiration = 3600

[sipcord]
type = endpoint
context = sipcord
allow = all
from_user = sipcord
from_domain = nottinghack.org.uk
outbound_auth = sipcord

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Studio Polycom SoundPoint 331 - 7883 / STUD
[7883]
type=endpoint
context=hack
allow=all
aors=7883

[7883](aor-single)

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Workshop Polycom SoundPoint 331 - 9675 / WORK
[9675]
type=endpoint
context=hack
allow=all
aors=9575

[9675](aor-single)

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Laser Polycom SoundPoint 331 - 739 / PEW
[739]
type=endpoint
context=hack
allow=all
aors=739

[739](aor-single)

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Electronics Area Polycom SoundPoint 331 - 3532 / ELEC
[3532]
type=endpoint
context=hack
allow=all
aors=3532

[3532](aor-single)

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Blue Room Polycom SoundPoint 331 - 2583 / BLUE
[2583]
type=endpoint
context=hack
allow=all
aors=2583

[2583](aor-single)


;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Art Room Polycom SoundPoint 331 - 278 / ART
[278]
type=endpoint
context=hack
allow=all
aors=278

[278](aor-single)

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Metalworking Downstairs Polycom SoundPoint 331 - 6385 / METL
[6385]
type=endpoint
context=hack
allow=all
aors=6385

[6385](aor-single)

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Studio Payphone Linksys SIP to POTS - 7464 / RING
[7464]
type=endpoint
context=hack
allow=all
aors=7464

[7464](aor-single)

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Aaron - 4225 / HACK
[4225]
type=endpoint
context=hack
allow=all
aors=4225

[4225](aor-single)

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Steve - 6667 / MOOP
[6667]
type=endpoint
context=hack
allow=all
aors=6667

[6667](aor-single)

